#!/bin/bash

echo "🔧 CORREÇÃO DO REPLIT DEPLOY"
echo ""
echo "✅ Arquivo index.html duplicado já foi removido da raiz"
echo ""
echo "📋 Mudanças a serem commitadas:"
git status --short

echo ""
echo "🚀 ESCOLHA UMA OPÇÃO:"
echo ""
echo "1. Usar Git Pane do Replit (RECOMENDADO)"
echo "   → Abra o Git Pane (ícone ⎇)"
echo "   → Commit: 'Fix Replit Deploy: Remove duplicate index.html'"
echo "   → Push"
echo ""
echo "2. Executar comandos Git manualmente:"
echo ""
echo "   git add -A"
echo "   git commit -m 'Fix Replit Deploy: Remove duplicate index.html'"
echo "   git push origin main"
echo ""
echo "3. Ou se já configurou credenciais:"
echo ""
echo "   git push \$GIT_URL"
echo ""
echo "📌 Após o push:"
echo "   • GitHub Actions vai deployar no Hostinger (automático)"
echo "   • Tente Replit Deploy novamente (manual - clique em Deploy)"
echo ""
